services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soat-fiap
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - api-data:/app/data
    environment:
      - SERVER_PORT=8080
      - DATABASE_PATH=/app/data/db.sqlite
      - LOG_LEVEL=info
      - SWAGGER_ENABLE=true
    command: ["go", "run", "./cmd/api/main.go"]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
